# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'rspec', '~> 3.9'
gem 'rack-test', '~> 1.1'
gem 'sinatra', '~> 2.0', '>= 2.0.8.1'
gem 'sequel', '~> 5.35'
gem 'sqlite3', '~> 1.4', '>= 1.4.2'